### PR TITLE
Fix crash on dump command

### LINKED ISSUE #439: Crash on ctx.call("DUMP", ...)
Call to RM_CALL with command DUMP crashes on reply

```rust
ctx.call("DUMP", &["a"]);
```

The crash happens in this method:

```rust
 pub fn call<'a, T: Into<StrCallArgs<'a>>>(&self, command: &str, args: T) -> RedisResult {
        self.call_internal::<_, CallResult>(command, raw::FMT, args)
            .map_or_else(|e| Err(e.into()), |v| Ok((&v).into()))
    }
```

```
thread '<unnamed>' (936142) panicked at /home/guy/.cargo/git/checkouts/redismodule-rs-0d6f86f5eaeafd9b/a670900/src/redisvalue.rs:236:84:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5, aborting


=== REDIS BUG REPORT START: Cut & paste starting from here ===
936142:M 21 Dec 2025 22:29:15.665 # Redis 8.2.3 crashed by signal: 6, si_code: -6
936142:M 21 Dec 2025 22:29:15.665 # Crashed running the instruction at: 0x7ffff6ea5fed

------ STACK TRACE ------
EIP:
/lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x11d) [0x7ffff6ea5fed]

936227 bio_lazy_free
/lib/x86_64-linux-gnu/libc.so.6(+0xac772) [0x7ffff6eac772]
/lib/x86_64-linux-gnu/libc.so.6(+0xa00ac) [0x7ffff6ea00ac]
/lib/x86_64-linux-gnu/libc.so.6(+0xa0807) [0x7ffff6ea0807]
/lib/x86_64-linux-gnu/libc.so.6(pthread_cond_wait+0x197) [0x7ffff6ea3067]
/home/linuxbrew/.linuxbrew/bin/redis-server *:6379(bioProcessBackgroundJobs+0x180) [0x5555556c1410]
/lib/x86_64-linux-gnu/libc.so.6(+0xa3d64) [0x7ffff6ea3d64]
/lib/x86_64-linux-gnu/libc.so.6(+0x1373bc) [0x7ffff6f373bc]

936208 rocksdb:high
/lib/x86_64-linux-gnu/libc.so.6(+0xac772) [0x7ffff6eac772]
/lib/x86_64-linux-gnu/libc.so.6(+0xa00ac) [0x7ffff6ea00ac]
/lib/x86_64-linux-gnu/libc.so.6(+0xa0807) [0x7ffff6ea0807]
/lib/x86_64-linux-gnu/libc.so.6(pthread_cond_wait+0x197) [0x7ffff6ea3067]
```

### PR DESCRIPTION
**Pull request by gkorland**
fix #439

### CODE REVIEW

File: examples/call.rs [hunk 1]
```diff
@@ -156,6 +156,34 @@ fn call_blocking_from_detach_ctx(ctx: &Context, _: Vec<RedisString>) -> RedisRes
     Ok(RedisValue::NoReply)
 }
 
+fn call_dump_test(ctx: &Context, _: Vec<RedisString>) -> RedisResult {
+    // Set a key with a value
+    ctx.call("SET", &["test_dump_key", "test_value"])?;
+
+    // Call DUMP which returns binary data (may not be valid UTF-8)
+    let dump_result = ctx.call("DUMP", &["test_dump_key"])?;
```
[the remark this answers is not in the document]
Comment (gkorland) [reply examples/call.rs]: DUMP is always on key name which is string.

File: examples/call.rs [hunk 2]
```diff
@@ -156,6 +156,34 @@ fn call_blocking_from_detach_ctx(ctx: &Context, _: Vec<RedisString>) -> RedisRes
...
+
+    // Verify we got a result (should be StringBuffer for binary data)
+    match dump_result {
+        RedisValue::StringBuffer(data) => {
+            if data.is_empty() {
+                return Err(RedisError::Str("DUMP returned empty data"));
+            }
```
Comment (oshadmi) [inline examples/call.rs]: Can also assert that `data` is invalid UTF-8 (otherwise should be a SimpleString), e.g.,
```assert!(std::str::from_utf8(&data).is_err(), "DUMP should return invalid UTF-8 data");```

Comment (oshadmi) [reply examples/call.rs]: I'll do it in a separate PR.

**Review by oshadmi — APPROVED** [review]
